services:
  web:
    build: .
    container_name: ${PROJECT_NAME}-web
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
      - "${ODOO_LONGPOLLING_PORT}:8072"
    volumes:
      # Modules (read-only)
      - ./addons/custom:/mnt/extra-addons/custom:ro
      - ./addons/oca:/mnt/extra-addons/oca:ro
      - ./addons/oca-addons:/mnt/extra-addons/oca-addons:ro

      # Config
      - ./odoo.conf:/etc/odoo/odoo.conf:ro

      # Data
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=${DB_HOST}
      - PORT=${DB_PORT}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ENABLE_GIT_AGGREGATE=false
    command: --dev=reload

  db:
    image: postgres:15
    container_name: ${PROJECT_NAME}-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"

volumes:
  odoo-web-data:
  postgres-data:
